### ISSUE TITLE
Announcement: Temporary Fix For (AttributeError: 'NoneType' object has no attribute 'group') in 3.0.0 Version

### ISSUE THREAD

**Issue by terryyz** [ssut/py-googletrans#280]
For anyone receives `NoneType' object has no attribute 'group`, if you are currently using `googletrans==3.0.0,` please switch to `googletrans==3.1.0a0` for the temporary fix.

Related Issue: #234

**Comment by mzeidhassan** [comment]
I am still having the same issue after installing googletrans==3.1.0a0

```
AttributeError                            Traceback (most recent call last)
<ipython-input-26-7d02fc64043f> in <module>
      1 from googletrans import Translator
      2 translator = Translator()
----> 3 print(translator.translate('أحبك', src='ar', dest= 'en'))

~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\client.py in translate(self, text, dest, src, **kwargs)
    180             jumps over  ->  이상 점프
    181             the lazy dog  ->  게으른 개
--> 182         """
    183         dest = dest.lower().split('_', 1)[0]
    184         src = src.lower().split('_', 1)[0]

~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\client.py in _translate(self, text, dest, src, override)
     76             self.token_acquirer = TokenAcquirer(
     77                 client=self.client, host=self.service_urls[0])
---> 78 
     79             #if we have a service url pointing to client api we force the use of it as defaut client
     80             for t in enumerate(service_urls):

~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\gtoken.py in do(self, text)
    192         if a < 0:  # pragma: nocover
    193             a = (a & 2147483647) + 2147483648
--> 194         a %= 1000000  # int(1E6)
    195 
    196         return '{}.{}'.format(a, a ^ b)

~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\gtoken.py in _update(self)
     60 
     61         try:
---> 62             # this will be the same as python code after stripping out a reserved word 'var'
     63             code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
     64             # unescape special ascii characters such like a \x3d(=)

AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by terryyz** [comment]
> I am still having the same issue after installing googletrans==3.1.0a0
> 
> ```
> AttributeError                            Traceback (most recent call last)
> <ipython-input-26-7d02fc64043f> in <module>
>       1 from googletrans import Translator
>       2 translator = Translator()
> ----> 3 print(translator.translate('أحبك', src='ar', dest= 'en'))
> 
> ~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\client.py in translate(self, text, dest, src, **kwargs)
>     180             jumps over  ->  이상 점프
>     181             the lazy dog  ->  게으른 개
> --> 182         """
>     183         dest = dest.lower().split('_', 1)[0]
>     184         src = src.lower().split('_', 1)[0]
> 
> ~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\client.py in _translate(self, text, dest, src, override)
>      76             self.token_acquirer = TokenAcquirer(
>      77                 client=self.client, host=self.service_urls[0])
> ---> 78 
>      79             #if we have a service url pointing to client api we force the use of it as defaut client
>      80             for t in enumerate(service_urls):
> 
> ~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\gtoken.py in do(self, text)
>     192         if a < 0:  # pragma: nocover
>     193             a = (a & 2147483647) + 2147483648
> --> 194         a %= 1000000  # int(1E6)
>     195 
>     196         return '{}.{}'.format(a, a ^ b)
> 
> ~\Anaconda3\envs\python3.7\lib\site-packages\googletrans\gtoken.py in _update(self)
>      60 
>      61         try:
> ---> 62             # this will be the same as python code after stripping out a reserved word 'var'
>      63             code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
>      64             # unescape special ascii characters such like a \x3d(=)
> 
> AttributeError: 'NoneType' object has no attribute 'group'
> ```

Hi @mzeidhassan, could you provide more information of your test environment. That translation actually worked for me at least...

**Comment by mzeidhassan** [comment]
Hi @terryyz 
Thanks for your follow-up. I don't have access to my home laptop at the moment, but I tested it on another machine, and indeed it is working fine now. Sorry about the false alarm. Thanks again for your support.

**Comment by huangyanxiong01** [comment]
The issue still in googletrans==3.1.0a0
```
Traceback (most recent call last):
  File "/home/freax/work/python/myfreax/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 63, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    tranlated = translator.translate('안녕하세요.', dest='ja')
  File "/home/freax/work/python/myfreax/venv/lib/python3.8/site-packages/googletrans/client.py", line 210, in translate
    data, response = self._translate(text, dest, src, kwargs)
  File "/home/freax/work/python/myfreax/venv/lib/python3.8/site-packages/googletrans/client.py", line 102, in _translate
    token = self.token_acquirer.do(text)
  File "/home/freax/work/python/myfreax/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 199, in do
    self._update()
  File "/home/freax/work/python/myfreax/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 67, in _update
    raise Exception('Could not find TKK token for this request.\nSee https://github.com/ssut/py-googletrans/issues/234 for more details.')
Exception: Could not find TKK token for this request.
See https://github.com/ssut/py-googletrans/issues/234 for more details.
```
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

```
(venv) ➜  myfreax git:(master) ✗ python --version
Python 3.8.5
```

```py
from googletrans import Translator
translator = Translator(service_urls=[
      'translate.google.cn',
    ])
tranlated = translator.translate('hello.', dest='zh-CN')
print(tranlated)
```
I can provide more information

**Comment by terryyz** [comment]
> ```python
> 'translate.google.cn'
> ```

Oops, I think most of the service_urls don't actually work in this version. But I'll check the issue thoroughly.

**Comment by huangyanxiong01** [comment]
```py
from googletrans import Translator
translator = Translator()
tranlated = translator.translate('hello.', dest='zh-CN')
print(tranlated)
```
This code have the same
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    tranlated = translator.translate('hello.', dest='zh-CN')
  File "/home/scrapyd/spiders/venv/lib/python3.8/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/home/scrapyd/spiders/venv/lib/python3.8/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/home/scrapyd/spiders/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/home/scrapyd/spiders/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group
```
Have you tested it in new environment? But is not your dev environment

**Comment by terryyz** [comment]
> ```python
> from googletrans import Translator
> translator = Translator()
> tranlated = translator.translate('hello.', dest='zh-CN')
> print(tranlated)
> ```
> 
> This code have the same
> 
> ```
> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     tranlated = translator.translate('hello.', dest='zh-CN')
>   File "/home/scrapyd/venv/lib/python3.8/site-packages/googletrans/client.py", line 182, in translate
>     data = self._translate(text, dest, src, kwargs)
>   File "/home/scrapyd/venv/lib/python3.8/site-packages/googletrans/client.py", line 78, in _translate
>     token = self.token_acquirer.do(text)
>   File "/home/scrapyd/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 194, in do
>     self._update()
>   File "/home/scrapyd/venv/lib/python3.8/site-packages/googletrans/gtoken.py", line 62, in _update
>     code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
> AttributeError: 'NoneType' object has no attribute 'group
> ```
> 
> Have you tested it in new environment? But is not your dev environment

I'm testing on Ubuntu 20.04 python3.8.5 and it works for the default setting.

**Comment by huangyanxiong01** [comment]
Sorry. I'm in error environment test. Now try again test and install `googletrans==3.1.0a0`. It's work well. But below the code can't wrok
```py
from googletrans import Translator
translator = Translator(service_urls=[
      'translate.google.cn',
    ])
tranlated = translator.translate('hello.', dest='zh-CN')
print(tranlated)
```

**Comment by terryyz** [comment]
> Sorry. I'm in error environment test. Now try again test and install `googletrans==3.1.0a0`. It's work well. But below the code can't wrok
> 
> ```python
> from googletrans import Translator
> translator = Translator(service_urls=[
>       'translate.google.cn',
>     ])
> tranlated = translator.translate('hello.', dest='zh-CN')
> print(tranlated)
> ```

Yes, that's what I was saying :)

**Comment by dougsouza** [comment]
If I use the default settings the translations work for a few requests, then translator return the same string I submitted. If I try to specify the service URL I get the error:

```
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/pytorch/lib/python3.7/site-packages/googletrans/gtoken.py in _update(self)
     62             # this will be the same as python code after stripping out a reserved word 'var'
---> 63             code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
     64             # unescape special ascii characters such like a \x3d(=)

AttributeError: 'NoneType' object has no attribute 'group'
```

Either way, it doesn't work.

**Comment by dangmanhtruong1995** [comment]
This worked, thanks a lot for your efforts !

**Comment by TheLastMonolith** [comment]
`googletrans==3.1.0a0` at python version 3.8.5 doesn't work for me.

**Comment by ratthachat** [comment]
work for me in Colab environment! Thanks so much!!

**Comment by LostInDarkMath** [comment]
I have a problem with this version. The text is not translated and the `translate` function returns the original text.
Example:
```python
>>> from googletrans import Translator
>>> translator = Translator()
>>> translator.translate(text='küche', dest='en')
Translated(src=en, dest=en, text=küche, pronunciation=küche, extra_data="{'translat...")
>>> translator.translate(text='küche', dest='en', src='de')
Translated(src=en, dest=en, text=küche, pronunciation=küche, extra_data="{'translat...")
```

I would expect `kitchen` as the correct translation. Is this a bug or am I doing sometimes wrong here?

**Comment by Bostwickenator** [comment]
I'm seeing the same behaviour @LostInDarkMath

**Comment by elfilalime** [comment]
The same problem @LostInDarkMath

**Comment by bianchi-dy** [comment]
Hi, I'm also getting the same issue even after changing the install version. On Python 3.7.6.

**Comment by ssut** [comment]
Hi folks!
Now I'm rewriting the entire codebase of this project in order to deal with rate-limiting, focusing on better stability, and reliability. This work can take some time but I'll try to complete it asap, so please be patient, and note that you all have to use the official [Google Cloud Translate](https://cloud.google.com/translate) API for production purposes even if fixes come out. Thank you all supporting this project, I'll bring back good news soon.

**Comment by ups1dedomn** [comment]
> Hi folks!
> Now I'm rewriting the entire codebase of this project in order to deal with rate-limiting, focusing on better stability, and reliability. This work can take some time but I'll try to complete it asap, so please be patient, and note that you all have to use the official [Google Cloud Translate](https://cloud.google.com/translate) API for production purposes even if fixes come out. Thank you all supporting this project, I'll bring back good news soon.

How is it going?

**Comment by gtkacz** [comment]
Hey there! Gettting the same problem as @LostInDarkMath even when translating _from_ english. Thanks for all your hard work!

**Comment by ups1dedomn** [comment]
While I look forward to the rewrite, I just got it working. My mistake was embarrassing! I didn't have wheel installed in my venv, so the install of this package failed. Just sharing in case others are stuck and getting the same issue.

Originally got the "NoneType not iterable" problem. After pip3 install wheel, this changed to "NoneType has not attribute group". After pip3 install googletrans==3.1.0a0 it worked.

Thanks for your work people :pray:

**Comment by vishnu4044** [comment]
after installing pip3 install googletrans==3.1.0a0.
still i'm not able to translate any text sir

my code
from googletrans import Translator
translator = Translator()  # initalize the Translator object
translations = translator.translate('see if this helps', dest='hi')  # translate two phrases to Hindi # print every translation
print(translations.text)

output:

see if this helps

**Comment by evan54** [comment]
do you know why pip still points to 3.0?

**Comment by Bostwickenator** [comment]
> do you know why pip still points to 3.0?

https://pip.pypa.io/en/stable/cli/pip_install/#pre-release-versions

**Comment by mzeidhassan** [comment]
For those who want to install 4.0.0rc1, you can this command:

`python -m pip install --pre googletrans`

**Comment by HubKing** [comment]
Sorry for interrupting but I have a question. I don't know a better place to ask this kind of question. Speech audio is currently not supported, is it? You know, if you go to Google Translate, and type something there is a speaker button that reads the text. I looked at the Network communication, and speech seems to be calling `https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?` and the response seems to contain some base64-looking encoded data, which is probably the audio data.

**Comment by liliana3186** [comment]
I just installed the version 4.0.0rc1 with python  3.7.6 and I still get same error 
anything else I need to do ?

**Comment by oleksandrsirenko** [comment]
Same error, neither version `3.1.0a0` nor `4.0.0rc1` works.

**Comment by JPH71** [comment]
When I try to install I get this error message
**pip install googletrans==3.1.0a0**

`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement googletrans==3.1.0a0 (from versions: 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.3.0, 2.4.0, 3.0.0)
ERROR: No matching distribution found for googletrans==3.1.0a0`

**Comment by ErichDs** [comment]
I tested a few versions of googletrans and seems to me that none of them are working anymore.

googletrans versions tested: 3.1.0a0; 4.0.0rc1 and the official version.

I'm using Python: 3.9.6

**Comment by NawtJ0sh** [comment]
if it aint working for yall anymore, you can try this instead #268

**Comment by JPH71** [comment]
Is there a version that will work with Python 2.7?

**Comment by NawtJ0sh** [comment]
> Is there a version that will work with Python 2.7?

Yes this does https://github.com/ssut/py-googletrans/issues/268 and it works with emojis also.

**Comment by JPH71** [comment]
Cheers Man!

**Comment by vicru** [comment]
> > For anyone receives `NoneType' object has no attribute 'group`, if you are currently using `googletrans==3.0.0,` please switch to `googletrans==3.1.0a0` for the temporary fix.
> > Related Issue: #234
> 
> Hi guys
> This problem has been solved in new version. please install 4.0.0rc1 version
> pip install googletrans==4.0.0rc1

`translator.translate('안녕하세요.', dest='ja')` returns `<googletrans.models.Translated at 0x1f5f0a51e80>`

**Comment by Practcdi** [comment]
For a quick fix try:- 
> (22-sep-2021)

`googletrans==3.1.0a0` 

It works for me :+1:

**Comment by user670** [comment]
Python 3.9 on Windows 10, neither 3.1.0a0 nor 4.0.0rc1 work

**Comment by vcuspinera** [comment]
On Mac with macOS Big Sur the same: neither 3.1.0a0 nor 4.0.0rc1 works

**Comment by nduprincekc** [comment]
Mine is working now

from googletrans import Translator
translator = Translator()
tranlated = translator.translate('hello.', dest='igbo')
print(tranlated.text)


# Nnọọ.

**Comment by yevonnaelandrew** [comment]
Working fine with me

!pip install googletrans==4.0.0rc1
from googletrans import Translator
translator = Translator()
translated = translator.translate(text='nama saya', dest='en')
print(translated.text)

If you just reinstalled the library, make sure to restart the runtime.

**Comment by VdeJong** [comment]
> I have a problem with this version. The text is not translated and the `translate` function returns the original text. Example:
> 
> ```python
> >>> from googletrans import Translator
> >>> translator = Translator()
> >>> translator.translate(text='küche', dest='en')
> Translated(src=en, dest=en, text=küche, pronunciation=küche, extra_data="{'translat...")
> >>> translator.translate(text='küche', dest='en', src='de')
> Translated(src=en, dest=en, text=küche, pronunciation=küche, extra_data="{'translat...")
> ```
> 
> I would expect `kitchen` as the correct translation. Is this a bug or am I doing sometimes wrong here?

I had this too, but then I noticed the response code was a 429 (Too many requests). I guess Google stops translating if that occurs. Check the response code of the response if a text is not translated.

**Comment by satwik-2001** [comment]
File "e:\python\speechrecognition.py", line 121, in <module>
    result = translator.translate('Mikä on nimesi', src='fi', dest='fr')
  File "E:\python\venv\lib\site-packages\googletrans\client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "E:\python\venv\lib\site-packages\googletrans\client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "E:\python\venv\lib\site-packages\googletrans\gtoken.py", line 194, in do
    self._update()
  File "E:\python\venv\lib\site-packages\googletrans\gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

this error is coming for pip install googletrans==4.0.0rc1 also can any one help me out

**Comment by nrbnlulu** [comment]
### use [this](https://pypi.org/project/translate-api/) library as it works fine

**Comment by laurinpaech** [comment]
I fixed it by updating my python version to 3.8.12

**Comment by leewanxian** [comment]
Hi,
Is there a proper solution for this?

```
AttributeError                            Traceback (most recent call last)
Cell In [27], line 1
----> 1 translator.detect('testing')

File C:\Anaconda\envs\dsi-sg\lib\site-packages\googletrans\client.py:255, in Translator.detect(self, text, **kwargs)
    252         result.append(lang)
    253     return result
--> 255 data = self._translate(text, 'en', 'auto', kwargs)
    257 # actual source language that will be recognized by Google Translator when the
    258 # src passed is equal to auto.
    259 src = ''

File C:\Anaconda\envs\dsi-sg\lib\site-packages\googletrans\client.py:78, in Translator._translate(self, text, dest, src, override)
     77 def _translate(self, text, dest, src, override):
---> 78     token = self.token_acquirer.do(text)
     79     params = utils.build_params(query=text, src=src, dest=dest,
     80                                 token=token, override=override)
     82     url = urls.TRANSLATE.format(host=self._pick_service_url())

File C:\Anaconda\envs\dsi-sg\lib\site-packages\googletrans\gtoken.py:194, in TokenAcquirer.do(self, text)
    193 def do(self, text):
--> 194     self._update()
    195     tk = self.acquire(text)
    196     return tk

File C:\Anaconda\envs\dsi-sg\lib\site-packages\googletrans\gtoken.py:62, in TokenAcquirer._update(self)
     59     return
     61 # this will be the same as python code after stripping out a reserved word 'var'
---> 62 code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
     63 # unescape special ascii characters such like a \x3d(=)
     64 code = code.encode().decode('unicode-escape')

AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by flacanellas** [comment]
This worked for me with `googletrans==3.1.0a0` at Ubuntu 20.04.5 LTS.

`pip3 uninstall googletrans`
`sudo pip3 uninstall googletrans`

PD: some times first install without sudo fails and I retry then with sudo.

Thx!

**Comment by v-danh** [comment]
> For anyone receives `NoneType' object has no attribute 'group`, if you are currently using `googletrans==3.0.0,` please switch to `googletrans==3.1.0a0` for the temporary fix.
> 
> Related Issue: #234

I think this package is no longer updated, right?

**Comment by JPH71** [comment]
You are right, I haven't updated it for a long while.
I hope the new version of Google translate is compatible with python 2.7

I will lo9k it into it this week as I have some enhancements to do

**Comment by v-danh** [comment]
> You are right, I haven't updated it for a long while. I hope the new version of Google translate is compatible with python 2.7 I will lo9k it into it this week as I have some enhancements to do

Dear **contributors**! 
Please consider removing Python **2x** support (please see at https://devguide.python.org/versions)

**Comment by JPH71** [comment]
Unfortunately plex is built around python 2.7...
So we are tied to that!

**Comment by black-six** [comment]
It works for me.

**Comment by Timothy1102** [comment]
version `3.1.0a0` not working for me. `4.0.0-rc1` works.

**Comment by bvn13** [comment]
still have such error using `3.1.0a0` and `4.0.0-rc1` both
