### ISSUE TITLE
`AttributeError` while using the `translate` method

### ISSUE THREAD

**Issue by RealA10N** [ssut/py-googletrans#251]
**Googletrans version:**
Tested both:
- [x] **3.0.0**
- [x] **2.4.0**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**

Installed googletrans today! When I tried to test the library by running the following script:
```python
from googletrans import Translator

t = Translator()
x = t.translate("hello", src="en", dest="su")
```

A strange error message popped up:
```
Traceback (most recent call last):
  File "f:/Projects/Programming/myprojectname/test.py", line 4, in <module>
    t.translate("hello", src="en", dest="su")
  File "C:\Users\PCNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\Users\PCNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans\client.py", line 75, 
in _translate
    token = self.token_acquirer.do(text)
  File "C:\Users\PCNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans\gtoken.py", line 200, in do
    self._update()
  File "C:\Users\PCNAME\AppData\Local\Programs\Python\Python36\lib\site-packages\googletrans\gtoken.py", line 65, 
in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Other information:**

Using Windows 10, Python 3.6.7

**Comment by jeiry** [comment]
same as u
I tried  translate -c hello

**Comment by RealA10N** [comment]
Sorry, duplicate of #234

**Comment by RealA10N** [comment]
**Fixed when updated to v3.1.0a0**
`pip install googletrans==3.1.0a0`
