### ISSUE TITLE
Type error when translating strings > 5k

### ISSUE THREAD

**Issue by jrabensc** [ssut/py-googletrans#274]
**Googletrans version:**
- [x] **3.x**
- [ ] **2.x**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
Got the 'AttributeError: 'NoneType' object has no attribute 'group' error and switched to 4.0.0-rc1 as described in https://github.com/ssut/py-googletrans/issues/234#issuecomment-748576711.

Got a type error when translating a string with len(string) > 5k

**Expected behavior:**
Translate strings up to len(string) = 15k

**Steps to reproduce:**

```python
%pip install googletrans==4.0.0-rc1
from lorem_text import lorem
from googletrans import Translator

translator = Translator()

text = lorem.words(1000)

print(len(text))
#7438

test = translator.translate(text[:5001], src = 'la', dest = 'en')
#TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

test = translator.translate(text[:5000], src = 'la', dest = 'en')

print(test)
#Translated(src=la, dest=en, text=which is refused to the devil [redacted]")
```
**Other information:**

```
3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0]`
```

**Comment by vesper8** [comment]
This only happens on `4.0.0-rc1`, it works fine on `3.1.0a0`

**Comment by he7d3r** [comment]
I don't think this should be wontfixed.
