### ISSUE TITLE
httpx lib has too old version (with security vulnerability)

### ISSUE THREAD

**Issue by diwert-ai** [ssut/py-googletrans#368]
**Googletrans version:**
- [x] **4.0.0rc1**
- [ ] **3.1.0a0**
- [ ] **3.0.0**
- [ ] **2.x**

**I'm submitting a bug report** 

- [x] bug report
- [ ] feature request

`googletrans` uses too old `httpx` library (version 0.13.3) which has a security vulnerability.
More info here https://github.com/advisories/GHSA-h8pj-cxx2-jfg2

But when i bumped httpx (from 0.13.3 to 0.23.0)  in my project there were errors when initializing the `googletrans` library:
```
File "E:\PyCharmProjects\TelegramBot\venv\lib\site-packages\googletrans\__init__.py", line 6, in <module>
    from googletrans.client import Translator
File "E:\PyCharmProjects\TelegramBot\venv\lib\site-packages\googletrans\client.py", line 25, in <module>
    class Translator:
File "E:\PyCharmProjects\TelegramBot\venv\lib\site-packages\googletrans\client.py", line 55, in Translator
    proxies: typing.Dict[str, httpcore.SyncHTTPTransport] = None, timeout: Timeout = None):
AttributeError: module 'httpcore' has no attribute 'SyncHTTPTransport'
```

**Comment by 123385918** [comment]
@diwert-ai  just install `googletrans-py==4.0.0` to resovle the issue.

**Comment by shiyishiaa** [comment]
> @diwert-ai just install `googletrans-py==4.0.0` to resovle the issue.

Pity. That author has no intention to maintain the project.
